"""initial schema

Revision ID: 6f1af01086be
Revises: 
Create Date: 2026-03-15 14:03:19.810636

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f1af01086be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions required before table creation
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('external_id', name=op.f('uq_users_external_id'))
    )
    op.create_index('ix_users_active', 'users', ['id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('goal_changes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('daily_energy_target_kj', sa.Double(), nullable=True),
    sa.Column('daily_protein_target_g', sa.Double(), nullable=True),
    sa.Column('daily_fat_target_g', sa.Double(), nullable=True),
    sa.Column('daily_carbs_target_g', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_changes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_changes'))
    )
    op.create_index('ix_goal_changes_user_effective', 'goal_changes', ['user_id', 'effective_from'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('eaten_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_index('ix_meals_user_id_eaten_at', 'meals', ['user_id', 'eaten_at'], unique=False)
    op.create_index('ix_meals_user_id_meal_type', 'meals', ['user_id', 'meal_type'], unique=False)
    op.create_table('nutrition_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_item', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('serving_amount', sa.Double(), server_default='1.0', nullable=False),
    sa.Column('serving_unit', sa.String(), server_default='g', nullable=False),
    sa.Column('serving_description', sa.Text(), nullable=True),
    sa.Column('energy_kj', sa.Double(), nullable=True),
    sa.Column('protein_g', sa.Double(), nullable=True),
    sa.Column('fat_g', sa.Double(), nullable=True),
    sa.Column('carbs_g', sa.Double(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('afcd_food_key', sa.Text(), nullable=True),
    sa.Column('base_entry_id', sa.UUID(), nullable=True),
    sa.Column('date_retrieved', sa.Date(), nullable=True),
    sa.Column('search_text', sa.Text(), sa.Computed("food_item || ' ' || coalesce(brand, '')", ), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_entry_id'], ['nutrition_entries.id'], name=op.f('fk_nutrition_entries_base_entry_id_nutrition_entries')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nutrition_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_entries'))
    )
    op.create_index('ix_nutrition_entries_afcd_food_key', 'nutrition_entries', ['afcd_food_key'], unique=False, postgresql_where='afcd_food_key IS NOT NULL')
    op.create_index('ix_nutrition_entries_embedding', 'nutrition_entries', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_nutrition_entries_search_text_trgm', 'nutrition_entries', ['search_text'], unique=False, postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.create_index('ix_nutrition_entries_source', 'nutrition_entries', ['source'], unique=False)
    op.create_index('ix_nutrition_entries_user_id', 'nutrition_entries', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_energy_target_kj', sa.Double(), nullable=True),
    sa.Column('daily_protein_target_g', sa.Double(), nullable=True),
    sa.Column('daily_fat_target_g', sa.Double(), nullable=True),
    sa.Column('daily_carbs_target_g', sa.Double(), nullable=True),
    sa.Column('timezone', sa.String(), server_default='Australia/Sydney', nullable=False),
    sa.Column('preferred_energy_unit', sa.String(), server_default='kj', nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.create_table('meal_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('nutrition_entry_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Double(), server_default='1.0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_items_meal_id_meals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nutrition_entry_id'], ['nutrition_entries.id'], name=op.f('fk_meal_items_nutrition_entry_id_nutrition_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_items'))
    )
    op.create_index('ix_meal_items_meal_id', 'meal_items', ['meal_id'], unique=False)
    op.create_index('ix_meal_items_nutrition_entry_id', 'meal_items', ['nutrition_entry_id'], unique=False)
    op.create_table('meal_photos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_photos_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_photos'))
    )
    op.create_index('ix_meal_photos_embedding', 'meal_photos', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where='embedding IS NOT NULL')
    op.create_index('ix_meal_photos_meal_id', 'meal_photos', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meal_photos_meal_id', table_name='meal_photos')
    op.drop_index('ix_meal_photos_embedding', table_name='meal_photos', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where='embedding IS NOT NULL')
    op.drop_table('meal_photos')
    op.drop_index('ix_meal_items_nutrition_entry_id', table_name='meal_items')
    op.drop_index('ix_meal_items_meal_id', table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_table('user_settings')
    op.drop_index('ix_nutrition_entries_user_id', table_name='nutrition_entries')
    op.drop_index('ix_nutrition_entries_source', table_name='nutrition_entries')
    op.drop_index('ix_nutrition_entries_search_text_trgm', table_name='nutrition_entries', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.drop_index('ix_nutrition_entries_embedding', table_name='nutrition_entries', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_nutrition_entries_afcd_food_key', table_name='nutrition_entries', postgresql_where='afcd_food_key IS NOT NULL')
    op.drop_table('nutrition_entries')
    op.drop_index('ix_meals_user_id_meal_type', table_name='meals')
    op.drop_index('ix_meals_user_id_eaten_at', table_name='meals')
    op.drop_table('meals')
    op.drop_index('ix_goal_changes_user_effective', table_name='goal_changes')
    op.drop_table('goal_changes')
    op.drop_index('ix_users_active', table_name='users', postgresql_where='deleted_at IS NULL')
    op.drop_table('users')
    # ### end Alembic commands ###
