"""Service-layer exceptions."""


class ServiceError(Exception): ...


class NotFoundError(ServiceError): ...


class ForbiddenError(ServiceError): ...


class DuplicateError(ServiceError): ...


class EmbeddingError(ServiceError): ...


class AuthenticationError(ServiceError): ...
